# Grids for hyperparameter/representation parameter search

GAPE_grid:
  rcut: [2.0, 2.5, 3.0]
  dim: [500, 1000]

SOAP_grid:
  rcut: [2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
  nmax: [1, 2, 3, 4, 5, 6, 7]
  lmax: [1, 2, 3, 4, 5, 6, 7]

GP_grid:
  kernel_degree: [1, 2, 3]
