model:
  _target_: src.predict_sklearn.SklearnGPRegressor
  data_loader:
    _target_: src.data_loader.DataLoader
  mode: write
  target_path:
    - ${data_root}/labels/train_test_split/indexed_targets_train.csv
    - ${data_root}/labels/train_test_split/indexed_targets_test.csv

training:
  kernel_degree: 2
  noise: 0.1
  save_fit: true
  stratify_train: true
  ard: false

testing:
  kernel_degree: 2
  noise: 0.1
