# Configuration of representations

# ChEAP
ChEAP_path_train: ${data_root}/representations/SIF/train/
ChEAP_path_test: ${data_root}/representations/SIF/test/

rescale_ChEAP: true
normalize: false

# GAPE
GAPE_path_train: ${data_root}/representations/APE_RF/train/
GAPE_path_test:  ${data_root}/representations/APE_RF/test/

smooth_cutoff: false
normalize_GAPE: false
rescale_GAPE: true

# SOAP
SOAP_path_train: ${data_root}/representations/SOAP/train/
SOAP_path_test:  ${data_root}/representations/SOAP/test/

normalize_SOAP: true
