#Configuration of representations

rep: SOAP # Type of reprsentation is None per default and
          # needs to be specified att runtime or when instantiating model

# ChEAP
ChEAP_paths: 
  - ${data_root}/representations/SIF/train/
  - ${data_root}/representations/SIF/test/

ChEAP_params:
  pauling_EN: EN
  nuclear_charge: Z 
  atomic_radius: r 
  qmol: qmol 
  valency: val 

rescale_ChEAP: true
normalize_ChEAP: false

# GAPE
GAPE_paths:
  - ${data_root}/representations/APE_RF/train/
  - ${data_root}/representations/APE_RF/test/

GAPE_params:
  rcut: 3.0 # cutoff
  dim: 500 # dimensionality

smooth_cutoff: false
normalize_GAPE: false
rescale_GAPE: true

# SOAP
SOAP_paths:
  - ${data_root}/representations/SOAP/train/
  - ${data_root}/representations/SOAP/test/

SOAP_params:
  rcut: 2.0 #rcut
  nmax: 3 # nmax
  lmax: 5 #lmax

normalize_SOAP: true
